### ISSUE TITLE
Elevator Movements

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#4]
Right now, the Door open and closing is synced well to the state of the door.
It would be great to show the elevator(s) going up and down. It _shouldn't_ be much different than the door animations, but there are some differences, e.g. the door has a finite number of states, but the floors are variable. 

Even if we limit the number of floors that are available, we'd still have to account for that, and that could make things a lot more complicated.

Alternatively, we could just show a light or something when an elevator is supposed to be on a floor, but it wouldn't be nearly as cool.

**Comment by josh-degraw** [comment]
I figured out a way to light up the arrows over the door when the elevator is moving.

**Comment by josh-degraw** [comment]
@maxraustin @nickarnett How do we want to show the elevator is moving? Do you guys want to show something like an elevator shaft next to the floors like we've basically set up, or can you guys think of better ways to do it?

**Comment by maxraustin** [comment]
Maybe next to the elevators we could have a graphic like an arrow or something which shows it going up or down. Can you swap a .gif file out during runtime? If so I can think of an easy way to do it that would look nice

**Comment by josh-degraw** [comment]
Yeah you can conditionally change properties depending on data. See the going up and going down icon above the elevator for example. That may be the best place to start.

**Comment by maxraustin** [comment]
I've found a new issue here and I think I understand why it happens, even if I don't know exactly how to fix it.
When you add multliple passengers onto the elevator on the same floor with different destinations, their path's all start with the same floor(makes sense). However, If you have a passenger get off on floor two but there's another guy who want to go to floor four(they both get on at floor one), the elevator thinks it needs to go back down to floor 1 and THEN up to floor four because the path value for that passenger still reads 1 to 4 when it should be reading 2 to 4.

Potential solution could be updating all the starting path values to the current floor. OR we could ignore the starting floor value in the passenger when deciding the Elevators movement path (since the elevator doesnt care where they started, it only cares where it is and where that passenger wants to go).

**Comment by nickarnett** [comment]
As long as the elevator knows where to pick up a new passenger i think we can probably get rid of the starting floor value. Our main goal is to track time spent, so path shouldn't really matter i guess.

**Comment by josh-degraw** [comment]
Yeah, I'm realizing that the whole path concept really only makes sense in an event-handler context. I'm refactoring that now.

**Comment by josh-degraw** [comment]
So I got the movements to work a bit better. @maxraustin I implemented some of the stuff we talked about today and was able to simplify a bunch of stuff. There are still some bugs, e.g. the Departed and Departing events sometimes get called a billion times in a row, but other than that it's looking pretty good.
