### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#5]
We need to make this prettier-- Design is probably my biggest weakness. We may want to draw up some more mockups of what the app could look like. I think that I've set up the display controls well enough that we shouldn't have to rework those too much.

**Comment by maxraustin** [comment]
I'll handle this issue, if you don't mind. Here is my current plan; in the space to the right of the elevators, I'm going to add an "interior" with information about who is in the elevator. It will have a little graphic of a person and a number next to it indicating how many people are in it and how close to full capacity it is. Does this sound like a good use of this region to you guys?

**Comment by josh-degraw** [comment]
I like it.

**Comment by maxraustin** [comment]
Okay so I've added the graphic of the elevator's interior next to the doors. It just has a person with a counter next to them showing how many people are inside it, and a number above the doors which will show the current floor like in a normal elevator. Currently this doesn't seem to work that great because we only update current floor when it arrives. I suspect this is an easy fix though.

**Comment by josh-degraw** [comment]
Cool you wanna push it up?
